export const DEV_MODE_REPORT = {
  title: 'Development Mode - Sample Report',
  subject: 'Development Testing Data',
  category: 'Software Testing & QA',
  aiProvider: 'Dev Mode Simulator',
  modelUsed: 'mock-gemini-dev-mode',
  confidenceScore: '99.9%',
  executiveSummary: 'This is a mocked report generated by the Development Test Mode. It verifies that the frontend pipeline can ingest, process, and display research data without consuming real API tokens.',
  identification: 'Primary Subject: QA Testing Mock Data.',
  detailedAnalysis: 'The development mode injects this structured JSON directly into the pipeline to bypass the Gemini network request. All subsequent processing steps—from rendering the viewer to saving history and generating PDFs—operate identically to a real API response.',
  historicalContext: 'Mock reports are an essential part of robust frontend development cycles.',
  scientificTechnicalInfo: 'Uses identical keys to standard Google Gemini responses mapped to the internal `reportData` interface.',
  applications: [
    'Verifying PDF Export formatting.',
    'Checking Dashboard metrics aggregation.',
    'Validating Archive local storage operations.',
    'Ensuring UI resilience when APIs are offline.'
  ],
  significance: 'Ensures UI resilience when APIs are offline and allows complete user journey testing.',
  keyFacts: [
    { label: 'Mode', detail: 'Development' },
    { label: 'Network', detail: 'Bypassed' },
    { label: 'Cost', detail: '$0.00' }
  ],
  references: [
    'Local System Test Fixture #1'
  ],
  conclusion: 'Development Mode is functioning correctly and successfully loaded the test payload.',
  visualAnalysisBullets: [
    "Detected Elements: Mock elements",
    "Colors & Lighting: N/A",
    "Composition & Framing: N/A",
    "Visible Features: Mock features",
    "Text Inscriptions: 'No readable text detected.'"
  ],
  backgroundInformation: "Detailed multi-paragraph explanation about the subject.",
  historicalScientificContext: "Factual historical, scientific, or evolutionary context.",
  keyCharacteristics: [
    { "label": "Key Feature 1", "detail": "Detail 1" },
    { "label": "Key Feature 2", "detail": "Detail 2" }
  ],
  applicationsImportance: [
    "Application 1",
    "Application 2"
  ],
  interestingFacts: [
    "Fact 1",
    "Fact 2"
  ],
  limitations: "Specific limitations of visual inference from this 2D representation alone.",
  detectedObjects: ["Feature 1", "Feature 2", "Feature 3"],
  extractedOCR: "Extracted text string OR 'No readable text detected.'",
  generatedKeywords: ["Tag1", "Tag2", "Tag3"]
};
